blueprint:
  name: "Universal EV: Auto Stop"
  description: "Disables balancing when EV charging power drops (indicating a full battery or manual stop)."
  domain: automation
  input:
    ev_charging_power_sensor:
      name: EV Actual Charging Power
      selector: { entity: { domain: sensor, device_class: power } }
    stop_wattage:
      name: Stop Threshold (Watts)
      default: 10
      selector: { number: { min: 0, max: 100, unit_of_measurement: W } }
    master_switch:
      name: Master Input Boolean
      selector: { entity: { domain: input_boolean } }

trigger:
  - platform: numeric_state
    entity_id: !input ev_charging_power_sensor
    below: !input stop_wattage
    for: "00:00:10"

condition:
  - condition: state
    entity_id: !input master_switch
    state: "on"

action:
  - action: input_boolean.turn_off
    target: { entity_id: !input master_switch }